pipeline:
  build:
    image: golang
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go get ./..
      - mkdir ./docker-bin
      - go build -ldflags '-extldflags "-static"' -o ./docker-bin/docker-registry-viewer
  docker:
    image: plugins/docker
    registry: registry.labs.0x.no
    repo: registry.labs.0x.no/docker-registry-viewer
    tags:
      - latest
